### ISSUE TITLE
BigQuery's field names have different requirements than jsontableschema's

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/tableschema-bigquery-py#10]
> [Required] The field name. The name must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_), and must start with a letter or underscore. The maximum length is 128 characters.
> https://cloud.google.com/bigquery/docs/reference/v2/tables

This means that there are data packages that can't be imported as is into BigQuery. In those cases, we must either convert jsontableschema's field names into ones usable by BigQuery, or at least catch the exception and warn the user.

I faced a very similar issue when developing ckanext-datapackager. A data package resource name must be usable in a URL, but a CKAN resource name doesn't. I had to slugify the resource names, then. Maybe we should do the same here?

@roll What do you think?

**Comment by pwalsh** [comment]
Unless this is a quick issue that @roll can fix, I rather you do it @vitorbaptista so Evgeny can stay in his current stream of work.

**Comment by roll** [comment]
Than we need `convert_name` and `restore_name` on that layer like there:

https://github.com/okfn/datapackage-sql-py/blob/master/dpsql/package.py#L134-L151

**Comment by roll** [comment]
@vitorbaptista @pwalsh 
It will be great if Vitor will be able to sort some things I missed thru PRs.

**Comment by vitorbaptista** [comment]
I'd be happy to do it :+1:

About the pattern of using `convert_*` and `restore_*`, I don't think we're able to restore the name here. First because slugifying is a destructive process (i.e. there's no way to revert it). Also, I'm supposing exporting from bigquery must work on any bigquery dataset, no matter if it was originally imported from a datapackage or not. That being the case, we should avoid messing with their attributes as much as we can IMHO.

**Comment by vitorbaptista** [comment]
Sent a PR at https://github.com/okfn/jsontableschema-bigquery-py/pull/11

**Comment by roll** [comment]
+1 about no restore

I've just pointed to naming convention - `convert` from upper level to lower and `restore` from lower to upper.

Thanks for the great PR!

FIXED
